### ISSUE TITLE
Installation hangs for SC, SP, and SI when upgrading from an old version

### ISSUE THREAD

**Issue by udidahan** [Particular/PlatformInstaller#202]
Even though issue #197 was resolved, the new installer hangs after it finishes the SC installation. After stopping the installer and restarting it, it showed that SC was installed successfully. Then the same thing happened with SP, as well as SI after it - hanging on each installation, where restarting the PI showed that it was actually successful.

**Comment by gbiellem** [comment]
@SimonCropp can you see if you can repro this?  I've tried and can't

**Comment by gbiellem** [comment]
@SimonCropp  nevermind I've figured out how to repro

**Comment by SimonCropp** [comment]
Details

**Comment by gbiellem** [comment]
This looks to be a bug in the Advanced Installer self extractors.   If the log file is specified on the command line the self extractor can hang after the installation is complete.  Since the PI waits for the child process to finish it does not proceed.

I can't repro this on my main machine but have been able to get it to hang in both silent mode and interactive mode on a test VM.  In interactive mode it shows an "Advanced Installer Enhanced UI"  exception dialog.  This only seems to occur if I specify a log file

I went hunting through Advanced Installer release notes and there seems to be a fix in 12.8  ( We use 12.6.1) for the packaging of SI SC SP and the NSB Powershell.

The bug is listed in there release notes [here](http://www.advancedinstaller.com/release-12.8.html)

I'll update Advanced Installer locally and repackage SC as test to see if this fixes it.

**Comment by gbiellem** [comment]
Seems to be fixed with locally repacked exes using Advanced  Installer 13.5 which is as high as we can go with our current license. 

I'll do more testing on Tuesday - @SimonCropp  I'll get you to do verify as well before I update the build agents

**Comment by gbiellem** [comment]
Build Agents have been updated to Advanced Installer 13.5

**Comment by gbiellem** [comment]
ServiceControl 1.38.0 and ServicePulse 1.8.7 have been released to fix this.
This can be closed once ServiceInsight 1.8.4 is released

**Comment by gbiellem** [comment]
All done!

**Comment by udidahan** [comment]
I've downloaded the new installer and everything was successful for me, so a big 👍 on getting this done.

Also, we're already seeing a significant decrease in the number of cancelled installations metric as well! 🎉
